{% set xorg_name = "libXaw3d" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.6.3" %}
{% set sha256 = "2dba993f04429ec3d7e99341e91bf46be265cc482df25963058c15f1901ec544" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ xorg_name }}-{{ version }}.tar.gz
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1002
  detect_binary_files_with_prefix: true

requirements:
  build:
    - m2-autoconf  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool  # [win]
    - m2w64-pkg-config  # [win]
    - pkg-config  # [not win]
    - posix  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - pthread-stubs
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - xorg-libxmu 1.1.*
    - xorg-libxt 1.1.*
    - xorg-util-macros
  run:
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - xorg-libxmu 1.1.*
    - xorg-libxt 1.1.*

test:
  commands:
    {% set lib_idents = [ "Xaw3d" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    - if not exist %PREFIX%/Library/bin/msys-{{ lib_ident }}-*.dll exit /b 1  # [win]
    {% endfor %}
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'The X.org X11 3D Athena widgets library.'

extra:
  recipe-maintainers:
    - pkgw
