travis:
  secure:
    BINSTAR_TOKEN: SHoVneS9VxkwHoWCPXoBJVRSemqSMYZy2yhhIimOjakjkh36T9sxQwSK9m5lWHbODuJ07uEwIylZljCIsj19tKFYe35kXqDLPLEBEbKgqy5XV8Qa2ruJF3IQz7dA1v8aDSHNtvjAhhYdOihza1iOuRsoK8Gqnd2WBWr1h9K3Gh6DwVhOldBuap3xnNH+AafiGmXAHdrNAHbOTaGvmL1Lhd6niRaVVpUBcRc04GPDqDeOR/9o4+FRIQ/If1sfrgLlI0u3MFoLlyKo/KPOoOSTbXnNJ8C0JhBi+XfkX6nVfo0MSJ59Zglk+DFN3LbJTjBPCEaZjCNJRkgTTIvBxdrkD7oPYIdb3bp90YDpTAYUfJL7f7R1yn9Qtqinp/SRO5VPfJTVLwbZzntrccz1mLLIZhoFruJ0kmLz507xp5NomQ7/4b6V3FK7rUnCx1Yiz+VdykpEWEfJDK+fe0K0wPqz4aL3fOur+8x0qDLTDLwFw0oByeWvKe49sDvldUUfxwfVLX0WBsL57dohQNMRvr8vtxNgar/Vsyvpwe4GjCPc8kQlx03mO186yCC3Fm4h/wKjMQPvKZtLZTYSyRnAT15YTbRkB+4YZXHXbzTx+pGiKbksKrfJFfWsNXXWj3zz1Y4bIL2yDHZWbYlUJr6TT7JRGtmFEp11R4Xzh/oeBHvc31I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
