travis:
  secure:
    BINSTAR_TOKEN: F0u8HB1RuOKw40qrLeXO5REAZv1pzJ/2Yc2YkR1SEXVYls1sSoPKl0d4mUKnRL57WNQ2GXoV1bK0tqTD7iiIlj1JYXLqZeYxHbfIlAPtT0H9VKSg7ruKcYKOtCjoufGNFSSl8K52wiB6ODp4ukEgKhtsIvxDz8sVjNJMLvIiSHYO3mIEn6gHd0ghl3TDDiH17SSVPDSyzZ+OMhAY7gq1oFQM5lXzZpNooAPUxJf2pVVZZEcBxsOwAxfSf3wVHaRKo9l8xpA2CKSs55DVPCMKBLxOL8i8Pf4eqlXiSl2jiLH3oKemMdHxEn9d75JDvk57tUkS3X4MKpfNM9vd8qVQw5CmNhMhQzEsuCEumtPKsgbWKS3XInj0esdOr6pT9SPFrTzsfIGoXFbnF9D7xBhNJmD1XQgCFdlZsH7vNPRiyPetec1lnqBdEgZJdL9AKfCEVFuO3nXspYKs1Tyz2jiBEMqbHEbX0UGry0ycNSFp7BVMx+Kv9/1PSm63dw4P7PnlLu8nEO0eANMh+yXjz7O/gMo4xjJH9mC11QDRFSQmac+fSI79V8WHer7VI3gE1eXHRV7uAzWEB/44oHeV7rQWd68vlGcS9VcZTELw20u9AMFJ93rr3B6GH+96bTe2uvJN5eIhN+hAl8Z69yROGYf7Tpp1UnxETWOys5If67VsPSc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
